# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8209cc182182ffa70b24afce24fc05331a6e97d027606d91e654c6ebfb126e7e8155948c0eae7f2a9539c41569a30b4b5eca0e3f718ed93cf27506a97897eb10

test:
  secret_key_base: 50e3b239b5d2804e437468437d4cd7838b3ceb7c812a94d70c9527e90bd5379c75bdf770cd3677e89d5934946515803fd55ae35e567bf63d856b8601f3a1780b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
